---

- hosts: all
  gather_facts: yes
  tasks:
  - debug:
      msg: "before run role"

# for openstack host
#  - import_role:
#      name: openstack-common
# for kvm host and bare metal host
#  - import_role:
#      name: openstack-common
# for dell server use only
#  - import_role:
#      name: dell-hwcheck
# for install cockpit use only 
#  - import_role:
#      name: install-cockpit
#
# for docker role
  - import_role:
      name: docker

# for consul client role
#  - import_role:
#      name: consul

#  - import_role:
#      name: install-salt-minion
#  - import_role:
#      name: update-falcon-agent
#
#
#       replace   java enviroment
#      sed -i s:/usr/local/java:/usr/java/default:g /etc/profile.d/java.sh
