#this playbook use to update openfalcon-agent  setting
#
- name: stop openfalcon-agent
  systemd: 
    name: openfalcon-agent
    state: stopped
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tags: stop openfalcon-agent

- name: stop openfalcon-agent for centos 6
  service:
    name: openfalcon-agent
    state: stopped
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  tags: start openfalcon-agent for centos 6

- name: modify setting
  script: modify-setting.sh
  tags: modify setting

- name: start openfalcon-agent for centos 6
  service:
    name: openfalcon-agent
    state: started
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  tags: start openfalcon-agent for centos 6

- name: start openfalcon-agent
  systemd: 
    name: openfalcon-agent
    state: started
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tags: start openfalcon-agent

